travis:
  secure:
    BINSTAR_TOKEN: g9hRiWfKQcxoF2IWlxaW8TUad5TVetF1aFLU3aj0x6ETsL9fKkg1LkfS6qx4J1sYjvkPo+wGSn4RvL4J0T6stiBqpo0R99Gf/8XPSZ106+y3QTal2omU2C3PYoGf0tQ3td4T++4/UOv7rhaCu3uB3HfBC6hl1MCQJ2DVCZZpo92+JjEFg9sMYaIryeP+SzeR2mc5MTu2aFKv90qv5pMQxPNlrKgxDltlOWgp9ULOLUrGNa9ecJj/xlW2BVkcTw9M5ambzIEXGUKR1KDISIpFPLugoH84OEpwEPPM5GOZhq7URdFZ6sKHVfJYa5F3Scal4hS0oBoRI8nWtHI/nLYm33Y4zOKutxgVO502VhFaqCkik0qn9j9g9ZIJs/MUH7LdsCdhthyL8sUPo0xvDFhSPJOW9aa34GyQitmxpye71uO6/ZZOvue6BxltRzCWW/pasKhrWaEngpWzqVFoEG3JEZXneASXjUHYDEPu3n9CZLOlMIGKgEGlQK8Dse/mWJWOpsaTj13EWF+Ir8RTxD6clFLMOyTZFWQQQHbu+q/sULUsE6q6uuQ7G8cdDpYw0FZgLBr4ayAu3qZjMoYc/aRkc4e5I6Fleak3jOq421+KatC9EIprLZukZbEyBceen7tf28E2ES7jgICwJHQhZgwRQY0bmUfX+Vc4vS6PIqnyXK8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
