travis:
  secure:
    BINSTAR_TOKEN: TbWVV7pwmPNoxC1ZBA91gAl94pxc8KKj5BQJuE175nE7cHNtsWYeCGpXTRRHa61JVwW7Q66HkkY4zYvj+jj6Fc4ySnYpEQwq8+4pHxeOjFvaRWVxQSV+8bTle1GPPPW5jEfwot7UijBLS+QPG+j4jhiMtWRZAIAkSMFo+SSI6PlCDwOXGJfhr8v6ocgYgAvG5IEUFXgOXAJiEfYbfA9T9jeTN+gc9OrmTjdMZzG2qnTzeq9aZO4M79ilP6Es1d7H5KXmMiOAva0ZlkjrXOYyw9Rox8tSjr2Xbkv1hN6Ae2ra4eFvXE7sOKlOnEf+jRBupOrFuYQCJ4CR9MbsidOe6tEZXliwSUCObCfcwJSFtZKF3cgwlsCy7zH5BYwybpmAQYIlzJRPlbqz8Gxzln47xe9+C8ogqWEGAQ9acKsyaLcbi2IIbXe3e/TS52U/JZFMkWfCqm4qrr/827TdyrBLsaxwyKNZ4xzI2ZvVfY8ANbLBfa7jsgB4yqE3hllV8/ZIMyatIrfzdzk4EhvD8VjYGcOQI3JL0hyVs+MAk0gZIj9HzAiZ+S0+5OVbTVQjMH4jJ4sREBpbra2Q9lrxDmwJQKP/gLxivqohpmqcLygoytrsY3ibn31o4rnhOiFM+Z8YSUCrYXa/dDvP92yx7XrO841h4IHLCXQJzMRZCXxYsLA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
